apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aro-operator-master
  name: aro-operator-master
  namespace: openshift-azure-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aro-operator-master
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: aro-operator-master
    spec:
      containers:
      - command:
        - aro
        args:
        - operator
        - master
        image: GENERATED
        name: aro-operator
        ports:
        - containerPort: 8080
          name: http
      nodeSelector:
        node-role.kubernetes.io/master: ""
      serviceAccountName: aro-operator-master
      priorityClassName: system-cluster-critical
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
