required = [
  "github.com/alvaroloes/enumer",
  "github.com/jim-minter/go-cosmosdb/cmd/gencosmosdb",
  "github.com/golang/mock/mockgen",
  "github.com/go-bindata/go-bindata/go-bindata",
  "golang.org/x/tools/cmd/goimports",
  "github.com/jstemmer/go-junit-report",
  "github.com/axw/gocov/gocov",
  "github.com/metal3-io/baremetal-operator/pkg/apis/metal3/v1alpha1",
  "github.com/AlekSi/gocov-xml",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/gengo/generator",
  "sigs.k8s.io/controller-tools/cmd/controller-gen",
]

[[constraint]]
  name = "github.com/alvaroloes/enumer"
  version = "1.1.2"

[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "42.1.0"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.17.1"

[[override]]
  name = "sigs.k8s.io/controller-tools"
  version = "v0.2.5"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  branch = "release-0.5"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.17"

[[constraint]]
  name = "k8s.io/gengo"
  revision = "f8a0810f38afb8478882b3835a615aebfda39afa"

[[override]]
  name = "github.com/containers/image"
  version = "v2.0.1"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.4.3"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.4"

[[constraint]]
  name = "github.com/openshift/api"
  branch = "release-4.4"

[[constraint]]
  name = "github.com/openshift/client-go"
  branch = "release-4.4"

[[override]]
  name = "github.com/openshift/cluster-api"
  branch = "release-4.4"

[[constraint]]
  name = "github.com/openshift/cluster-api-provider-azure"
  branch = "release-4.4"

[[constraint]]
  name = "github.com/openshift/installer"
  branch = "release-4.4-azure"
  source = "https://github.com/jim-minter/installer"

# Matches Installer used version (master)
# Should go away in 4.5 with move to go modules
[[override]]
  name = "github.com/openshift/cloud-credential-operator"
  revision = "a443c1b9c73a79a25c8fd3c37bfdd08c009b7d6d"

[[override]]
  branch = "release-4.4"
  name = "github.com/openshift/machine-api-operator"
  source = "github.com/openshift/machine-api-operator"

[[override]]
  name = "github.com/openshift/machine-config-operator"
  branch = "release-4.4"

[[constraint]]
  name = "github.com/openshift/console-operator"
  branch = "release-4.4"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/ugorji/go"
  version = "1.1.7"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[override]]
  branch = "release-4.4"
  name = "github.com/metal3-io/baremetal-operator"
  source = "https://github.com/openshift/baremetal-operator"


[[override]]
  name = "k8s.io/api"
  branch = "origin-4.4-kubernetes-1.17.1"
  source = "https://github.com/openshift/kubernetes-api"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "origin-4.4-kubernetes-1.17.1"
  source = "https://github.com/openshift/kubernetes-apimachinery"

[[override]]
  name = "k8s.io/client-go"
  branch = "origin-4.4-kubernetes-1.17.1"
  source = "https://github.com/openshift/kubernetes-client-go"

[[override]]
  name = "sigs.k8s.io/cluster-api-provider-azure"
  branch = "release-4.4"
  source = "https://github.com/openshift/cluster-api-provider-azure"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "github.com/openshift/installer"
    unused-packages = false
