apiVersion: v1
kind: List
items:
- apiVersion: security.openshift.io/v1
  kind: SecurityContextConstraints
  metadata:
    name: privileged-ifreload
  allowHostDirVolumePlugin: true
  allowHostIPC: true
  allowHostNetwork: true
  allowHostPID: true
  allowHostPorts: true
  allowPrivilegeEscalation: true
  allowPrivilegedContainer: true
  allowedCapabilities:
  - '*'
  allowedUnsafeSysctls:
  - '*'
  fsGroup:
    type: RunAsAny
  readOnlyRootFilesystem: false
  requiredDropCapabilities: null
  runAsUser:
    type: RunAsAny
  seLinuxContext:
    type: RunAsAny
  seccompProfiles:
  - '*'
  supplementalGroups:
    type: RunAsAny
  users:
  - system:serviceaccount:openshift-azure-ifreload:default
  volumes:
  - '*'
- apiVersion: v1
  kind: Namespace
  metadata:
    name: openshift-azure-ifreload
    annotations:
      openshift.io/node-selector: ""
- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    name: ifreload
    namespace: openshift-azure-ifreload
  spec:
    selector:
      matchLabels:
        app: ifreload
    template:
      metadata:
        labels:
          app: ifreload
      spec:
        containers:
        - image: docker.io/jimminter/ifreload:latest
          imagePullPolicy: Always
          name: ifreload
          securityContext:
            privileged: true
        hostNetwork: true
        tolerations:
        - effect: NoExecute
          operator: Exists
        - effect: NoSchedule
          operator: Exists
