# Azure DevOps Job deploying rp
parameters:
  fullDeploy: ''

jobs:
- deployment: Deploy
  variables:
  - template: ../vars.yml
  pool:
    vmImage: ubuntu-latest
  environment: RP-INT
  strategy:
    runOnce:
      deploy:
        steps:
        - template: ./template-deploy-azure-env.yml
          parameters:
            fullDeploy: ${{ parameters.fullDeploy }}
