# Azure DevOps Pipeline deploying the azure hosted environment
trigger: none
pr: none

parameters:
- name: fullDeploy
  type: boolean
  default: false

jobs:
- template: ./templates/template-job-deploy-azure-env.yml
  parameters:
    fullDeploy: ${{ parameters.fullDeploy }}
